KNOWLEDGE_POINTS = [
    {
        "id": 0,
        "name": "孟德尔遗传定律",
        "importance": 5,
        "difficulty": 4,
        "core_requirement": "会判断显隐性、分离比、基因型和表现型",
        "sort_order": 1,
    },
    {
        "id": 1,
        "name": "减数分裂与受精作用",
        "importance": 5,
        "difficulty": 5,
        "core_requirement": "会分析染色体、DNA、染色单体数量变化",
        "sort_order": 2,
    },
    {
        "id": 2,
        "name": "伴性遗传",
        "importance": 5,
        "difficulty": 4,
        "core_requirement": "会分析红绿色盲、抗维生素D佝偻病等遗传图解",
        "sort_order": 3,
    },
    {
        "id": 3,
        "name": "DNA是主要遗传物质",
        "importance": 5,
        "difficulty": 3,
        "core_requirement": "掌握肺炎链球菌转化实验、噬菌体侵染细菌实验",
        "sort_order": 4,
    },
    {
        "id": 4,
        "name": "DNA结构与复制",
        "importance": 5,
        "difficulty": 4,
        "core_requirement": "掌握双螺旋、碱基互补配对、半保留复制",
        "sort_order": 5,
    },
    {
        "id": 5,
        "name": "基因指导蛋白质合成",
        "importance": 5,
        "difficulty": 5,
        "core_requirement": "掌握转录、翻译、密码子、氨基酸关系",
        "sort_order": 6,
    },
    {
        "id": 6,
        "name": "基因表达与性状关系",
        "importance": 4,
        "difficulty": 4,
        "core_requirement": "理解基因、蛋白质、性状之间的关系",
        "sort_order": 7,
    },
    {
        "id": 7,
        "name": "基因突变和基因重组",
        "importance": 4,
        "difficulty": 4,
        "core_requirement": "区分突变、重组及其在变异中的意义",
        "sort_order": 8,
    },
    {
        "id": 8,
        "name": "染色体变异",
        "importance": 4,
        "difficulty": 4,
        "core_requirement": "掌握结构变异、数目变异、染色体组",
        "sort_order": 9,
    },
    {
        "id": 9,
        "name": "人类遗传病",
        "importance": 4,
        "difficulty": 3,
        "core_requirement": "会区分单基因、多基因、染色体异常遗传病",
        "sort_order": 10,
    },
    {
        "id": 10,
        "name": "基因在染色体上",
        "importance": 4,
        "difficulty": 3,
        "core_requirement": "理解萨顿假说、摩尔根果蝇实验",
        "sort_order": 11,
    },
    {
        "id": 11,
        "name": "现代生物进化理论",
        "importance": 4,
        "difficulty": 4,
        "core_requirement": "掌握自然选择、基因频率、物种形成",
        "sort_order": 12,
    },
    {
        "id": 12,
        "name": "生物共同祖先证据",
        "importance": 3,
        "difficulty": 2,
        "core_requirement": "掌握化石、比较解剖学、胚胎学等证据",
        "sort_order": 13,
    },
    {
        "id": 13,
        "name": "协同进化与生物多样性",
        "importance": 3,
        "difficulty": 3,
        "core_requirement": "理解共同进化和生物多样性的形成",
        "sort_order": 14,
    },
    {
        "id": 14,
        "name": "探究实践与模型实验",
        "importance": 3,
        "difficulty": 3,
        "core_requirement": "会解释模拟实验、观察实验和调查实验目的",
        "sort_order": 15,
    },
]

KNOWLEDGE_POINT_BY_ID = {item["id"]: item for item in KNOWLEDGE_POINTS}
